<?php

return [
    'app_name' => 'EOS Tools',
    'timezone' => 'Asia/Jakarta',
    'session_key' => 'eos_tools_user',
    'users' => [
        'halotec' => 'halotec',
    ],
    'telegram' => [
        'bot_token' => '6924587019:AAGAL14FraFfWSA4kR_lIwWY5T6rlk1UagE',
        'chat_ids' => ['-1002149116231', '-1125589160', '-4166697858'],
        'poll_state_file' => __DIR__ . '/storage/state/telegram_offset.json',
        'webhook_key' => 'eos-tools-secure-key',
        'bot_name' => 'EOS Tools',
        'aliases' => ['eos', 'eos tools', 'eostools', 'bot eos', 'boot', '@boot'],
        'include_responder_identity' => true,
    ],
    'disk' => [
        'drive' => 'C:',
        'threshold_percent' => 5,
        'state_file' => __DIR__ . '/storage/state/disk_monitor.json',
    ],
    'network' => [
        'timeout_seconds' => 2,
        'state_file' => __DIR__ . '/storage/state/network_monitor.json',
        'notify_on_change' => true,
        'targets' => [
            [
                'key' => 'pulau_payung',
                'label' => 'Server Pulau Payung',
                'type' => 'ping',
                'host' => '10.15.42.34',
            ],
            [
                'key' => 'server_cloud',
                'label' => 'Server Cloud',
                'type' => 'ping',
                'host' => '172.27.0.21',
            ],
            [
                'key' => 'lb_server',
                'label' => 'LB Server',
                'type' => 'ping',
                'host' => '172.27.0.36',
            ],
            [
                'key' => 'cusmod_domain',
                'label' => 'CUSMOD Domain',
                'type' => 'http',
                'url' => 'https://cusmod-ca.multiterminal.co.id/',
            ],
            [
                'key' => 'ca_cam_3in',
                'label' => 'CA Cam 3IN',
                'type' => 'ping',
                'host' => '10.116.224.48',
            ],
            [
                'key' => 'ca_cam_3out',
                'label' => 'CA Cam 3OUT',
                'type' => 'ping',
                'host' => '10.116.224.48',
            ],
        ],
    ],
    'controller' => [
        'state_file' => __DIR__ . '/storage/state/controller_state.json',
        'auto_disarm_after_fire' => true,
        'commands' => [
            'restart_pool',
            'restart_group',
            'restart_iis',
            'disk_report',
            'telegram_ping',
            'image_fetch',
        ],
    ],
    'iis' => [
        'app_pools' => [
            'AMS',
            'AMSGCP',
            'CGSIN',
            'CGSIN01',
            'CGSIN02',
            'CGSINGCP',
            'CGSINUAT',
            'CGSOUT',
            'CGSOUT01',
            'CGSOUTGCP',
            'CGSOUTUAT',
            'CGSMANUAL',
            'CMSERVICE',
            'CustomsRepo',
            'CustomsRepoGCP',
            'Monitoring',
        ],
        'restart_groups' => [
            'CGSIN_STACK' => ['CGSIN', 'CGSIN01', 'CGSIN02', 'CGSINGCP', 'CGSINUAT'],
            'CGSOUT_STACK' => ['CGSOUT', 'CGSOUT01', 'CGSOUTGCP', 'CGSOUTUAT'],
            'CORE_SERVICES' => ['AMS', 'AMSGCP', 'CMSERVICE', 'CustomsRepo', 'CustomsRepoGCP', 'Monitoring'],
        ],
    ],
    'images' => [
        'cache_dir' => __DIR__ . '/storage/cache',
        'cache_url_base' => 'storage/cache',
        'roots' => [
            '\\\\10.15.42.141\\autogate_ca_server\\GatePict\\%gate%\\%date%\\',
            '\\\\10.15.42.141\\autogate_ca_server\\AutogatePictures\\%gate%\\%date%\\',
        ],
        'gates' => [
            'GATE02I', 'GATE03I', 'GATE04I', 'GATE05I', 'GATE06I', 'GATE07I',
            'GATE01O', 'GATE02O', 'GATE03O', 'GATE04O', 'GATE05O', 'GATE06O',
        ],
        'max_results' => 24,
    ],
    'devices' => [
        'cameras' => [
            ['gate_id' => 'GATE01I', 'ip' => '10.116.224.102', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE01O', 'ip' => '10.116.225.12', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE02I', 'ip' => '10.116.224.30', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE02O', 'ip' => '10.116.225.30', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE03I', 'ip' => '10.116.224.48', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE03O', 'ip' => '10.116.225.46', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'FRONT', 'action' => ''],
            ['gate_id' => 'GATE03O', 'ip' => '10.116.225.48', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE04I', 'ip' => '10.116.224.63', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'FRONT', 'action' => ''],
            ['gate_id' => 'GATE04O', 'ip' => '10.116.225.63', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'FRONT', 'action' => ''],
            ['gate_id' => 'GATE05I', 'ip' => '10.116.224.81', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'FRONT', 'action' => ''],
            ['gate_id' => 'GATE05O', 'ip' => '10.116.225.84', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE06I', 'ip' => '10.116.224.102', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE06O', 'ip' => '10.116.225.84', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => 'mirror'],
            ['gate_id' => 'GATE07I', 'ip' => '10.116.224.102', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'BACK', 'action' => ''],
            ['gate_id' => 'GATE08I', 'ip' => '10.116.1.177', 'model' => 'SONY', 'auth_profile' => 'sony_blank', 'name' => 'FRONT', 'action' => ''],
            ['gate_id' => 'GATE08I', 'ip' => '10.116.224.119', 'model' => 'AXIS', 'auth_profile' => 'axis_root', 'name' => 'RIGHT', 'action' => ''],
            ['gate_id' => 'GATE11O', 'ip' => '10.116.1.204', 'model' => 'HIKVISION', 'auth_profile' => 'hikvision_admin', 'name' => 'BUFFER', 'action' => ''],
        ],
        'gates' => [
            ['id' => 'GATE01I', 'gate_name' => 'Gate 01 IN', 'zone' => 'E', 'io' => 'I', 'barrier_ip' => '10.116.224.7', 'timbangan_ip' => '10.116.3.11'],
            ['id' => 'GATE01O', 'gate_name' => 'Gate 01 OUT', 'zone' => 'E', 'io' => 'O', 'barrier_ip' => '10.116.225.7', 'timbangan_ip' => '10.116.3.11'],
            ['id' => 'GATE02I', 'gate_name' => 'Gate 02 IN', 'zone' => 'E', 'io' => 'I', 'barrier_ip' => '10.116.224.25', 'timbangan_ip' => '10.116.3.12'],
            ['id' => 'GATE02O', 'gate_name' => 'Gate 02 OUT', 'zone' => 'E', 'io' => 'O', 'barrier_ip' => '10.116.225.25', 'timbangan_ip' => '10.116.3.12'],
            ['id' => 'GATE03I', 'gate_name' => 'Gate 03 IN', 'zone' => 'E', 'io' => 'I', 'barrier_ip' => '10.116.224.43', 'timbangan_ip' => '10.116.3.13'],
            ['id' => 'GATE03O', 'gate_name' => 'Gate 03 OUT', 'zone' => 'E', 'io' => 'O', 'barrier_ip' => '10.116.225.43', 'timbangan_ip' => '10.116.3.13'],
            ['id' => 'GATE04I', 'gate_name' => 'Gate 04 IN', 'zone' => 'E', 'io' => 'I', 'barrier_ip' => '10.116.224.61', 'timbangan_ip' => '10.116.3.14'],
            ['id' => 'GATE04O', 'gate_name' => 'Gate 04 OUT', 'zone' => 'I', 'io' => 'O', 'barrier_ip' => '10.116.225.61', 'timbangan_ip' => '10.116.3.14'],
            ['id' => 'GATE05I', 'gate_name' => 'Gate 05 IN', 'zone' => 'E', 'io' => 'I', 'barrier_ip' => '10.116.224.79', 'timbangan_ip' => '10.116.3.15'],
            ['id' => 'GATE05O', 'gate_name' => 'Gate 05 OUT', 'zone' => 'E', 'io' => 'O', 'barrier_ip' => '10.116.225.79', 'timbangan_ip' => '10.116.3.15'],
            ['id' => 'GATE06I', 'gate_name' => 'Gate 06 IN', 'zone' => 'E', 'io' => 'I', 'barrier_ip' => '10.116.224.97', 'timbangan_ip' => '10.116.3.16'],
            ['id' => 'GATE06O', 'gate_name' => 'Gate 06 OUT', 'zone' => 'E', 'io' => 'O', 'barrier_ip' => '10.116.225.97', 'timbangan_ip' => '10.116.3.16'],
            ['id' => 'GATE07I', 'gate_name' => 'Gate 07 IN', 'zone' => 'I', 'io' => 'I', 'barrier_ip' => '10.116.224.115', 'timbangan_ip' => '10.116.3.17'],
            ['id' => 'GATE08I', 'gate_name' => 'Gate 08 IN', 'zone' => 'I', 'io' => 'I', 'barrier_ip' => '10.116.224.215', 'timbangan_ip' => '10.116.3.18'],
        ],
        'auth_profiles' => [
            'axis_root' => ['username' => 'LOCAL_ONLY', 'password' => 'LOCAL_ONLY'],
            'sony_blank' => ['username' => 'LOCAL_ONLY', 'password' => 'LOCAL_ONLY'],
            'hikvision_admin' => ['username' => 'LOCAL_ONLY', 'password' => 'LOCAL_ONLY'],
        ],
    ],
    'paths' => [
        'storage' => __DIR__ . '/storage',
        'logs' => __DIR__ . '/storage/logs',
        'app_log' => __DIR__ . '/storage/logs/activity.log',
        'telegram_log' => __DIR__ . '/storage/logs/telegram.log',
        'network_log' => __DIR__ . '/storage/logs/network.log',
    ],
    'runtime' => [
        'responder_label' => 'AUTO',
        'responder_ip' => 'AUTO',
    ],
];
